name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          GOOS="darwin" GOARCH="amd64" go build -o pikpakdav-darwin-amd64
          GOOS="darwin" GOARCH="arm64" go build -o pikpakdav-darwin-arm64
          GOOS="linux" GOARCH="amd64" go build -o pikpakdav-linux-amd64
          GOOS="linux" GOARCH="arm64" go build -o pikpakdav-linux-arm64
          GOOS="windows" GOARCH="amd64" go build -o pikpakdav-windows-amd64.exe
          GOOS="windows" GOARCH="arm64" go build -o pikpakdav-windows-arm64.exe

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            pikpakdav-*
